services:
  - type: web
    name: doctweak-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FRONTEND_URL
        value: https://doctweaker.vercel.app